// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Data;

#nullable disable

namespace TechStore.Migrations
{
    [DbContext(typeof(TechStoreDbContext))]
    partial class TechStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Laptops, monitores y equipos para estudio y trabajo.",
                            Imagen = "cat-computadoras.svg",
                            Nombre = "Computadoras"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Teléfonos y tablets de las marcas más buscadas.",
                            Imagen = "cat-smartphones.svg",
                            Nombre = "Smartphones"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Audífonos, smartwatches y complementos para tu día a día.",
                            Imagen = "cat-accesorios.svg",
                            Nombre = "Accesorios"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Teclados, mouse y periféricos para jugar mejor.",
                            Imagen = "cat-gaming.svg",
                            Nombre = "Gaming"
                        });
                });

            modelBuilder.Entity("TechStore.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Ryzen 5, 16 GB RAM y SSD de 512 GB. Ideal para estudio y trabajo.",
                            Estado = true,
                            Imagen = "laptop.svg",
                            Nombre = "Laptop Lenovo IdeaPad 3",
                            Precio = 649.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Pantalla AMOLED de 6.4\", cámara de 50 MP y batería de 5000 mAh.",
                            Estado = true,
                            Imagen = "smartphone.svg",
                            Nombre = "Smartphone Samsung Galaxy A54",
                            Precio = 379.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Inalámbricos, con hasta 50 horas de batería y buen aislamiento.",
                            Estado = true,
                            Imagen = "headphones.svg",
                            Nombre = "Audífonos Sony WH-CH520",
                            Precio = 59.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descripcion = "Switches rojos, retroiluminación e ideal para escribir y jugar.",
                            Estado = true,
                            Imagen = "keyboard.svg",
                            Nombre = "Teclado Mecánico Redragon Kumara",
                            Precio = 42.50m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descripcion = "Sensor de 8000 DPI, RGB configurable y diseño ligero.",
                            Estado = true,
                            Imagen = "mouse.svg",
                            Nombre = "Mouse Gamer Logitech G203",
                            Precio = 29.99m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descripcion = "GPS, monitor de salud y hasta 10 días de batería.",
                            Estado = true,
                            Imagen = "smartwatch.svg",
                            Nombre = "Smartwatch Amazfit Bip 5",
                            Precio = 89.90m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Descripcion = "Full HD, 144 Hz y 1 ms. Pensado para gaming fluido.",
                            Estado = true,
                            Imagen = "monitor.svg",
                            Nombre = "Monitor LG UltraGear 24\"",
                            Precio = 179.00m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Descripcion = "Pantalla de 11\", 128 GB de almacenamiento y sonido cuádruple.",
                            Estado = true,
                            Imagen = "tablet.svg",
                            Nombre = "Tablet Xiaomi Redmi Pad SE",
                            Precio = 199.99m,
                            Stock = 9
                        });
                });

            modelBuilder.Entity("TechStore.Models.Producto", b =>
                {
                    b.HasOne("TechStore.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TechStore.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
